account: ${oc.env:SLURM_ACCOUNT,""}
partition: ${oc.env:SLURM_PARTITION,""}
time: "00:20:00"
ntasks_per_node: 1
gpus_per_node: 4
gres: "gpu:4"
output: ${output_dir}/%j.out   # ${oc.env:OUTPUT_DIR,""}/%j.out
nodes: 1

total_gpus: ${oc.muli:${.nodes},${.gpus_per_node}}
template: "dummy.sh"